### ISSUE TITLE
Forwarded process not receiving data when Duplicated process is down

### ISSUE THREAD

**Issue by synio-wesley** [agnoster/duplicator#12]
I have two TCP servers, one running at :39000 and one running at :29000. The duplicator is started on :9000 and forwards traffic to :39000 and duplicates traffic to :29000. I am using the duplicator to receive live data on the newer TCP server which is in development.

However, when the newer TCP server crashes or is not online, the live TCP server does not receive any data anymore either. I get a lot of error messages saying "BufferedStream is already ended". For my purpose, the TCP server at :29000 can restart often or crash, but the live server at :39000 must keep receiving data. This is very important. Any way to fix this?

**Comment by Kanakala** [comment]
@profoX @agnoster, I have the same problem. Can someone help me solving the issue!!

**Comment by isul** [comment]
@agnoster @demmer @synio-wesley @Kanakala Same here, and the following code will fix it.

line number 98 at index.js
//buffer.end()
if (client.connected && !buffer.ended)
                buffer.end()

**Comment by synio-wesley** [comment]
Thanks for the workaround. I'm closing this issue because it's been 4.5 years and I'm not working with it anymore.
